# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dba5a061f49718767bb51f560f07a7eb4fa9cb0a3ce6e7aa70243f0a75b41327e1c81f3dae9cbca92963832dabdbe66e26a5a1a06656a7761b449d1a5bdf6c39

test:
  secret_key_base: 6135a1d449aa2cd16d4b6e676c8763208e8507dc3ece4369d2e95edf745f944abe32dba3821929337041d80e3343f9d998378b2a5afff38e90f5296141481553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
